name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release name (optional, defaults to tag name)'
        required: false
        type: string
      release_body:
        description: 'Release body/notes (optional)'
        required: false
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: FreeGameNotifications
          path: ./artifacts/

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name || github.event.inputs.tag_name }}
          body: ${{ github.event.inputs.release_body }}
          draft: true
          prerelease: ${{ contains(github.event.inputs.tag_name, '-pre') || contains(github.event.inputs.tag_name, '-rc') }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ # Path to your artifact
          asset_name: ${{ listFiles(format('./artifacts/'))[0] }}
          asset_content_type: application/octet-stream # Or your asset's content type
